apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  type: LoadBalancer  # Use NodePort if you don't want a LoadBalancer
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 4499  # Port on the container
