apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: dvpatil250/test-c1:latest
        ports:
        - containerPort: 4499
